<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\JustHangingAround.Shared\JustHangingAround.Shared.csproj" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Services\ApiClient.cs">
	    <Generator>MSBuild:Compile</Generator>
	  </Compile>
	</ItemGroup>

</Project>